language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly-2018-05-31
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - rustup install nightly-2018-05-31
  - cargo +nightly-2018-05-31 install clippy --force
  - cargo +nightly-2018-05-31 install rustfmt-nightly --force

script:
  - cargo test
  - cargo +nightly-2018-05-31 clippy
  - cargo +nightly-2018-05-31 fmt -- --check

git:
  depth: 1

notifications:
  email:
    on_success: never

